export const CART_ADD_PRODUCTS = "CART_ADD_PRODUCTS";
export const CART_REMOVE_PRODUCTS = "CART_REMOVE_PRODUCTS";
export const CART_SAVE_SHIPPING_INFO = "CART_SAVE_SHIPPING_INFO";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
export const CART_CLEAR_PRODUCTS = "CART_CLEAR_PRODUCTS";