
export default{
    CART_ADD_PRODUCTS : "CART_ADD_PRODUCTS",
    CART_REMOVE_PRODUCTS : "CART_REMOVE_PRODUCTS",
    CART_SAVE_SHIPPING_INFO : "CART_SAVE_SHIPPING_INFO",
    CART_SAVE_PAYMENT_METHOD : "CART_SAVE_PAYMENT_METHOD",
    CART_CLEAR_PRODUCTS : "CART_CLEAR_PRODUCTS",
}
export const CART_ADD_PRODUCTS_REQUEST = "CART_ADD_PRODUCTS_REQUEST";
export const CART_ADD_PRODUCTS_SUCCESS = "CART_ADD_PRODUCTS_SUCCESS";
export const CART_ADD_PRODUCTS_FAIL = "CART_ADD_PRODUCTS_FAIL";

export const CART_REMOVE_PRODUCTS_REQUEST = "CART_REMOVE_PRODUCTS_REQUEST";
export const CART_REMOVE_PRODUCTS_SUCCESS = "CART_REMOVE_PRODUCTS_SUCCESS";
export const CART_REMOVE_PRODUCTS_FAIL = "CART_REMOVE_PRODUCTS_FAIL";