
export default{
    ORDER_CREATE_REQUEST : "ORDER_CREATE_REQUEST",
    ORDER_CREATE_SUCCESS : "ORDER_CREATE_SUCCESS",
    ORDER_CREATE_FAIL : "ORDER_CREATE_FAIL",
    ORDER_CREATE_RESET : "ORDER_CREATE_RESET",

    ORDER_DETAIL_REQUEST : "ORDER_DETAIL_REQUEST",
    ORDER_DETAIL_SUCCESS : "ORDER_DETAIL_SUCCESS",
    ORDER_DETAIL_FAIL : "ORDER_DETAIL_FAIL",

    GET_SINGLE_ORDER_REQUEST : "GET_SINGLE_ORDER_REQUEST",
    GET_SINGLE_ORDER_SUCCESS : "GET_SINGLE_ORDER_SUCCESS",
    GET_SINGLE_ORDER_FAIL : "GET_SINGLE_ORDER_FAIL",
}
