export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";

export const PRODUCT_SEARCH_REQUEST = "PRODUCT_SEARCH_REQUEST";
export const PRODUCT_SEARCH_SUCCESS = "PRODUCT_SEARCH_SUCCESS";
export const PRODUCT_SEARCH_FAIL = "PRODUCT_SEARCH_FAIL"

export const PRODUCT_GET_FEEDBACK_REQUEST = "PRODUCT_GET_FEEDBACK_REQUEST";
export const PRODUCT_GET_FEEDBACK_SUCCESS = "PRODUCT_GET_FEEDBACK_SUCCESS";
export const PRODUCT_GET_FEEDBACK_FAIL = "PRODUCT_GET_FEEDBACK_FAIL"

export const PRODUCT_CREATE_FEEDBACK_REQUEST = "PRODUCT_CREATE_FEEDBACK_REQUEST";
export const PRODUCT_CREATE_FEEDBACK_SUCCESS = "PRODUCT_CREATE_FEEDBACK_SUCCESS";
export const PRODUCT_CREATE_FEEDBACK_FAIL = "PRODUCT_CREATE_FEEDBACK_FAIL"
export const PRODUCT_CREATE_FEEDBACK_RESET = "PRODUCT_CREATE_FEEDBACK_RESET"