export default {
    PRODUCT_LIST_REQUEST : "PRODUCT_LIST_REQUEST",
    PRODUCT_LIST_SUCCESS : "PRODUCT_LIST_SUCCESS",
    PRODUCT_LIST_FAIL : "PRODUCT_LIST_FAIL",

    PRODUCT_DETAIL_REQUEST : "PRODUCT_DETAIL_REQUEST",
    PRODUCT_DETAIL_SUCCESS : "PRODUCT_DETAIL_SUCCESS",
    PRODUCT_DETAIL_FAIL : "PRODUCT_DETAIL_FAIL",

    PRODUCT_SEARCH_REQUEST : "PRODUCT_SEARCH_REQUEST",
    PRODUCT_SEARCH_SUCCESS : "PRODUCT_SEARCH_SUCCESS",
    PRODUCT_SEARCH_FAIL : "PRODUCT_SEARCH_FAIL",

    PRODUCT_GET_FEEDBACK_REQUEST : "PRODUCT_GET_FEEDBACK_REQUEST",
    PRODUCT_GET_FEEDBACK_SUCCESS : "PRODUCT_GET_FEEDBACK_SUCCESS",
    PRODUCT_GET_FEEDBACK_FAIL : "PRODUCT_GET_FEEDBACK_FAIL",

    PRODUCT_CREATE_FEEDBACK_REQUEST : "PRODUCT_CREATE_FEEDBACK_REQUEST",
    PRODUCT_CREATE_FEEDBACK_SUCCESS : "PRODUCT_CREATE_FEEDBACK_SUCCESS",
    PRODUCT_CREATE_FEEDBACK_FAIL : "PRODUCT_CREATE_FEEDBACK_FAIL",
    PRODUCT_CREATE_FEEDBACK_RESET : "PRODUCT_CREATE_FEEDBACK_RESET",
}