export default {
    CREATE_SHOP_REQUEST : "CREATE_SHOP_REQUEST",
    CREATE_SHOP_SUCCESS : "CREATE_SHOP_SUCCESS",
    CREATE_SHOP_FAIL : "CREATE_SHOP_FAIL",
    
    GET_SHOP_REQUEST : "GET_SHOP_REQUEST",
    GET_SHOP_SUCCESS : "GET_SHOP_SUCCESS",
    GET_SHOP_FAIL : "GET_SHOP_FAIL",
}