export default {
    CREATE_SHOP_REQUEST : "CREATE_SHOP_REQUEST",
    CREATE_SHOP_SUCCESS : "CREATE_SHOP_SUCCESS",
    CREATE_SHOP_FAIL : "CREATE_SHOP_FAIL",
    
    GET_SHOP_REQUEST : "GET_SHOP_REQUEST",
    GET_SHOP_SUCCESS : "GET_SHOP_SUCCESS",
    GET_SHOP_FAIL : "GET_SHOP_FAIL",

    GET_SHOP_INFOR_REQUEST : "GET_SHOP_INFOR_REQUEST",
    GET_SHOP_INFOR_SUCCESS : "GET_SHOP_INFOR_SUCCESS",
    GET_SHOP_INFOR_FAIL : "GET_SHOP_INFOR_FAIL",

    PRODUCT_SHOP_LIST_REQUEST : "PRODUCT_SHOP_LIST_REQUEST", // get product theo id Shop
    PRODUCT_SHOP_LIST_SUCCESS : "PRODUCT_SHOP_LIST_SUCCESS",
    PRODUCT_SHOP_LIST_FAIL : "PRODUCT_SHOP_LIST_FAIL",
}