export default{
    GET_SHOP_INFOR_REQUEST : "GET_SHOP_INFOR_REQUEST",
    GET_SHOP_INFOR_SUCCESS : "GET_SHOP_INFOR_SUCCESS",
    GET_SHOP_INFOR_FAIL : "GET_SHOP_INFOR_FAIL",

    PRODUCT_SHOP_LIST_REQUEST : "PRODUCT_SHOP_LIST_REQUEST",
    PRODUCT_SHOP_LIST_SUCCESS : "PRODUCT_SHOP_LIST_SUCCESS",
    PRODUCT_SHOP_LIST_FAIL : "PRODUCT_SHOP_LIST_FAIL",
}
