export default {
    USER_LOGIN_REQUEST : "USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS : "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL : "USER_LOGIN_FAIL",
    USER_LOGOUT : "USER_LOGOUT",

    USER_REGISTER_REQUEST : "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS : "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAIL : "USER_REGISTER_FAIL",

    USER_DETAIL_REQUEST : "USER_DETAIL_REQUEST",
    USER_DETAIL_SUCCESS : "USER_DETAIL_SUCCESS",
    USER_DETAIL_FAIL : "USER_DETAIL_FAIL",
    USER_DETAIL_RESET : "USER_DETAIL_RESET",

    USER_UPDATE_USER_IMAGE_REQUEST : "USER_UPDATE_USER_IMAGE_REQUEST",
    USER_UPDATE_USER_IMAGE_SUCCESS : "USER_UPDATE_USER_IMAGE_SUCCESS",
    USER_UPDATE_USER_IMAGE_FAIL : "USER_UPDATE_USER_IMAGE_FAIL",

    USER_UPDATE_PROFILE_REQUEST : "USER_UPDATE_PROFILE_REQUEST",
    USER_UPDATE_PROFILE_SUCCESS : "USER_UPDATE_PROFILE_SUCCESS",
    USER_UPDATE_PROFILE_FAIL : "USER_UPDATE_PROFILE_FAIL",

    USER_CHECK_PASS_REQUEST : "USER_CHECK_PASS_REQUEST",
    USER_CHECK_PASS_SUCCESS : "USER_CHECK_PASS_SUCCESS",
    USER_CHECK_PASS_FAIL : "USER_CHECK_PASS_FAIL",
}